import { StyleSheet } from "react-native";
import { colors, fontSize, radius, spacing } from "@/theme/theme";

export const profileHeroStyles = StyleSheet.create({
  hero: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: radius.card,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarShell: { width: 120, height: 120, borderRadius: 60, alignItems: "center", justifyContent: "center" },
  avatarImage: { width: 120, height: 120, borderRadius: 60, borderWidth: 2, borderColor: colors.border },
  initialsAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  initialsText: { color: colors.accent, fontSize: 42, fontWeight: "800" },
  cameraBadge: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.background,
  },
  cameraBadgeText: { color: "#111", fontWeight: "800" },
  name: { marginTop: spacing.md, color: colors.textPrimary, fontSize: fontSize.lg, fontWeight: "800" },
  email: { color: colors.textSecondary, marginTop: spacing.xs },
  meta: { color: colors.success, marginTop: spacing.sm, fontWeight: "700" },
  shieldText: { marginTop: spacing.sm, color: colors.textSecondary, fontSize: fontSize.sm },
  uploadCard: {
    backgroundColor: colors.card,
    borderRadius: radius.card,
    padding: spacing.md,
    borderColor: colors.border,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "center",
  },
  uploadText: { color: colors.textSecondary, fontWeight: "700" },
  statsRow: { flexDirection: "row", gap: spacing.md },
});
