import { StyleSheet } from "react-native";
import { colors, fontSize, radius, spacing } from "@/theme/theme";

/** Shared styles for lesson exercise panels (card, MCQ, code fill, line ordering, find-bug). */
export const exerciseViewStyles = StyleSheet.create({
  root: { flex: 1 },
  exerciseCard: {
    backgroundColor: colors.card,
    borderRadius: radius.card,
    borderColor: colors.border,
    borderWidth: 1,
    padding: spacing.lg,
  },
  explanation: { color: colors.textSecondary, lineHeight: 22 },
  hint: { color: colors.textSecondary, lineHeight: 22, marginBottom: spacing.xs },
  option: {
    padding: spacing.md,
    borderRadius: radius.button,
    borderColor: colors.border,
    borderWidth: 1,
    marginTop: spacing.sm,
  },
  optionLabel: { color: colors.textPrimary },
  correct: { borderColor: colors.success, backgroundColor: "rgba(78,205,196,0.2)" },
  wrong: { borderColor: colors.danger, backgroundColor: "rgba(255,107,107,0.2)" },
  optionSelected: { borderColor: colors.accent },
  lessonButton: {
    backgroundColor: colors.accent,
    padding: spacing.md,
    borderRadius: radius.button,
    alignItems: "center",
    marginTop: spacing.md,
  },
  lessonButtonLabel: { color: "#111", fontWeight: "800" },
  disabled: { opacity: 0.5 },
  feedback: { marginTop: spacing.md, fontWeight: "700", color: colors.textPrimary },
  feedbackGood: { color: colors.success },
  feedbackBad: { color: colors.danger },
  findBugLineRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  findBugLineSelected: { borderColor: colors.accent },
  monospaceLineText: { color: colors.textPrimary, fontFamily: "monospace" },
  lineOrderingAnswerZone: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.card,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  lineOrderingSectionTitle: { color: colors.textSecondary, fontWeight: "700", marginBottom: spacing.sm },
  lineOrderingEmptyHint: { color: colors.textSecondary, marginTop: spacing.md },
  lineOrderingSelectedRow: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: radius.button,
    padding: spacing.md,
    marginBottom: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(247,223,30,0.08)",
  },
  lineOrderingRemoveGlyph: { color: colors.danger, fontSize: fontSize.md, fontWeight: "800" },
  lineOrderingPoolRow: {
    padding: spacing.md,
    borderRadius: radius.button,
    borderColor: colors.border,
    borderWidth: 1,
    marginTop: spacing.sm,
  },
  lineOrderingSecondaryButton: {
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    padding: spacing.md,
    alignItems: "center",
  },
  lineOrderingSecondaryButtonLabel: { color: colors.textPrimary, fontWeight: "700" },
  codePuzzleTextInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  codePuzzleTokenRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.md },
  codePuzzleTokenChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  codePuzzleTokenChipLabel: { color: colors.accent, fontSize: fontSize.sm },
});
