import { StyleSheet } from "react-native";
import { colors, fontSize, radius, spacing } from "@/theme/theme";

export const x = StyleSheet.create({
  hearts: { fontSize: fontSize.lg, marginBottom: spacing.sm },
  line: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  lineSelected: { borderColor: colors.accent },
  lineText: { color: colors.textPrimary, fontFamily: "monospace" },
  answerZone: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.card,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  answerZoneTitle: { color: colors.textSecondary, fontWeight: "700", marginBottom: spacing.sm },
  answerPreview: { color: colors.textSecondary, marginTop: spacing.md },
  selectedLine: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: radius.button,
    padding: spacing.md,
    marginBottom: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(247,223,30,0.08)",
  },
  removeIcon: { color: colors.danger, fontSize: fontSize.md, fontWeight: "800" },
  poolOption: {
    padding: spacing.md,
    borderRadius: radius.button,
    borderColor: colors.border,
    borderWidth: 1,
    marginTop: spacing.sm,
  },
  secondaryAction: {
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    padding: spacing.md,
    alignItems: "center",
  },
  secondaryActionLabel: { color: colors.textPrimary, fontWeight: "700" },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  suggestionRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.md },
  token: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  tokenText: { color: colors.accent, fontSize: fontSize.sm },
});
